# Uncomment the next line to define a global platform for your project

platform :ios, '10.0'
inhibit_all_warnings!

target 'MoyaPractice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MoyaPractice

  pod 'Moya'
  pod 'ObjectMapper'
  
  target 'MoyaPracticeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MoyaPracticeUITests' do
    # Pods for testing
  end

end
